### ISSUE TITLE
JSONTypeHintField works only in one direction with subclasses

### ISSUE THREAD

**Issue by manuelbernhardt** [sphereio/sphere-scala-libs#10]
I have only tested this quickly but I have the nagging feeling that

``` scala
@JSONTypeHintField("fooType")
sealed trait Foo
case class(bar: String) extends Foo
```

Works only in one direction, i.e. when parsing the incoming JSON string, but not when serialising it.

**Comment by OlegIlyenko** [comment]
Thanks for reporting this! I guess that the classes you want to serialize/deserialize look like this:

    @JSONTypeHintField("fooType")
    sealed trait Foo
    case class FooSubtype(bar: String) extends Foo

This kind of code works fine for many of our usages. There are some pitfalls though. You need to make sure that you import annotations from right package. In my experience this can cause some issues. Can you please test with following imports:

    import io.sphere.json._
    import io.sphere.json.generic._

I would be also helpful if you could show the resulting JSON (the result of serialization).

**Comment by manuelbernhardt** [comment]
Sorry for the late reply on this one.

I tried with the imports above but to no avail, the resulting JSON still contains the `type` field:

    {"id":"550d8f72d4c62f87e235923c","tables":["550c1bd1d4c69c374569e6ca"],"floor":"550c1bc4d4c69c374569e6c5","min":1,"max":2,"user":"550c1b43d4c69c374569e6b8","timestamp":"2015-03-21T15:34:10.589Z","type":"GroupAdded"}

With the following annotation:

```scala
@JSONTypeHintField("foo")
sealed trait UserEvent extends Event {
  def timestamp: DateTime
  def user: ObjectId
}
```

The import resolves to the type alias `JSONTypeHintField` define in the package object `io.spehere.json.generic`

I'm not entirely sure why the annotation isn't taken into account, though I do remember having debugged the code and never having seen in step through any place looking for the annotation in the case of a sealed trait as super-type.

**Comment by yanns** [comment]
I could reproduce your error.
A current workaround is to use an abstract class instead of a trait:

```scala
@JSONTypeHintField("foo")
sealed abstract class UserEvent extends Event {
  def timestamp: DateTime
  def user: ObjectId
}
```
